name: Build & Deploy to GitHub Pages
on:
  push:
    branches: ['main'] # Or "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npm run build -- --base-href=/xfdf-annotator-angular/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/xfdf-annotator-angular
