name: Build & Deploy to GitHub Pages
on:
  push:
    branches: ['main'] # Or "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx ng deploy --base-href=/xfdf-annotator-angular/ --name="Syed Haffiz" --email="haffizsyed@gmail.com"
